name: Sync Development to Main

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  rebase-development-onto-main:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Fetch all branches
        run: git fetch origin

      - name: Checkout main branch
        run: git checkout main

      - name: Rebase development onto main
        run: |
          git checkout development
          git rebase main

      - name: Push changes to main
        run: |
          git checkout main
          git merge development --ff-only
          git push origin main

      - name: Handle rebase conflicts
        if: failure()
        run: |
          echo "⚠️  There was a conflict during the rebase. Please resolve it manually."
          exit 1
