name: Sync Development to Main

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  sync-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Setup SSH Keys and known_hosts
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$DEPLOY_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Fetch all branches
        run: git fetch origin

      - name: Checkout main branch
        run: git checkout main

      - name: Rebase development onto main
        run: |
          git checkout development
          git rebase main

      - name: Push changes to main
        run: |
          git checkout main
          git merge development --ff-only
          git push git@github.com:${GITHUB_REPOSITORY}.git main

      - name: Handle rebase conflicts
        if: failure()
        run: |
          echo "⚠️  There was a conflict during the rebase. Please resolve it manually."
          exit 1
